//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int contactID { get; set; }
        public string fullName { get; set; }
        public string email { get; set; }
        public string title { get; set; }
        public string detail { get; set; }
        public System.DateTime dateCreate { get; set; }
        public bool status { get; set; }
        public string phone { get; set; }
    }
}
